version: "3.9"
services:
  server:
    build:
      context: ./backend/
    command: npm start
    volumes:
      - ./backend/:/usr/server
      - /usr/server/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "8000:6379"
      - "8001:8001"
  mongo:
    image: "mongo:6.0"
    ports:
      - "27017:27017"
  client:
    build:
      context: ./frontend/
    command: npm start
    volumes:
      - ./frontend/:/usr/client
      - /usr/client/node_modules
    depends_on:
      - server
    ports:
      - "3001:3001"